### ISSUE TITLE
Long press 'a' key to repeatedly type 'a'

### ISSUE THREAD

**Issue by noahjutz** [dkter/aaaaa#11]
I would like for the keyboard to repeatedly enter 'a's when I long press the 'a' key.

I've already created a prototype:

https://user-images.githubusercontent.com/30440621/118447439-10ca5080-b6f1-11eb-8f08-0be8a35c0870.mp4

It's still a little rough around the edges, but I was wondering if you would accept a pull request once I clean up the code.

**Comment by dkter** [comment]
this is great! maybe make the capital As a toggleable option, but I'd love to see a PR for this
