### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by Donnnno** [dkter/aaaaa#16]
This great app deserves a good icon, so I gave it a try:

![image](https://user-images.githubusercontent.com/31142286/130450354-00ab7838-8efc-495e-8d5e-80147e6f3f07.png)

**Comment by dkter** [comment]
This looks great! Do you have an SVG of this?

**Comment by Donnnno** [comment]
Hi! Cool, of course. I can also make a pull request directly with all the assets needed :^)

**Comment by mondlicht-und-sterne** [comment]
@dkter     If this appears in fdroid, I will paint it as an acrylic picture with the name of @Donnnno

**Comment by dkter** [comment]
@mondlicht-und-sterne it's been released and should be there soon (I just realized I screwed up the previous release so I redid it).

**Comment by Donnnno** [comment]
> @dkter     If this appears in fdroid, I will paint it as an acrylic picture with the name of @Donnnno 

Wow haha, great!
