### ISSUE TITLE
Add exclamation point

### ISSUE THREAD

**Issue by nek0bit** [dkter/aaaaa#2]
*What I expected:* aaaaaaaaaaaaaaaaaaaaaaaaaa!

*What actually happened:* aaaaaaaaaaaaaaaaaaaaaaaaaa

This is wonderful software, but it's very disappointing that it doesn't have an exclamation point. There are some cases where I would like to express excitement, but it does not seem to be available. Do you think we could get an exclamation point? I understand this software is made with free time, so please take as much time as you need.

**Comment by dkter** [comment]
I'll add it to the backlog
