### ISSUE TITLE
add w key

### ISSUE THREAD

**Issue by 6058aa27-6ced-4d77-952a-bf55d59351c2** [dkter/aaaaa#31]
While `a` alone gives ample room for communication, even simply adding `w` widely expands the range of possibilities. Consider: awawawa, awwwww, waaaaa, etc.

This would be create a positive future for the app, expanding it's uses and accessibility, for example it would make it more accessible to dolls. Thank you for understanding.

**Comment by dkter** [comment]
While I do see the potential in adding w, I'm concerned about an extra key creating further confusion. As it is, there are already almost too many possible things to say (a, aaa, aaaaaa, aaaaaaaaaaaaaaaaa, etc.) Adding another key would exponentially increase the number of ideas that can be expressed, which may be overwhelming to many of our current users.

If you'd like to explore this potential on your own, however, forks are strongly encouraged. I'm excited to see what possibilities a keyboard with w added would bring.

**Comment by 6058aa27-6ced-4d77-952a-bf55d59351c2** [comment]
Of course, I understand the concern. It might be beneficial to explore this in my own fork to observe any potential consequences or usability concerns, and see if they outweigh the benefits of the additional key. I'll keep you posted.

¡Hasta luego!
