### ISSUE TITLE
Keyboard shows an uppercase A but types a lowercase a 

### ISSUE THREAD

**Issue by Amr512** [dkter/aaaaa#8]
Please fix this it's literally unusable if I tap something but type something else how am I supposed to tell what letter I'm typing 
![Screenshot_20210423_062545_org mozilla firefox](https://user-images.githubusercontent.com/30956223/115818280-c3620880-a3fc-11eb-99ac-965841ad1511.jpg)

**Comment by dkter** [comment]
that's weird, on my system it shows a lowercase a. i'll look into it

**Comment by dkter** [comment]
could you let me know what device you're using?

**Comment by Amr512** [comment]
A huawei nova 5t (which is the same as the honor 20 pro)

**Comment by dkter** [comment]
should be addressed in the next release!
